from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
import joblib

texts = [
    # ── Food ──────────────────────────────────
    "pizza dinner",
    "burger meal",
    "restaurant lunch",
    "cafe breakfast",
    "chinese takeout",
    "biryani order",
    "mcdonalds",
    "kfc chicken",
    "subway sandwich",
    "dominos pizza",
    "swiggy food order",
    "zomato dinner",
    "sushi restaurant",
    "pasta dinner",
    "coffee shop",
    "starbucks coffee",
    "food delivery",
    "dine out",
    "hotel breakfast",
    "snacks evening",
    "ice cream parlour",
    "juice bar",
    "ice cream",
    "kulfi",
    "lassi",
    "chai tea",
    "samosa",
    "pani puri",
    "vada pav",
    "thali",
    "dosa breakfast",
    "idli sambhar",
    "paratha",
    "chole bhature",
    "rajma chawal",
    "noodles",
    "momos",
    "rolls kathi",
    "maggi noodles",
    "poha",
    "upma",
    "dhaba lunch",
    "street food",
    "chaat",
    "bhel puri",
    "pav bhaji",
    "paneer dinner",
    "butter chicken",
    "dal makhani",
    "halwa sweet",
    "gulab jamun",
    "jalebi",
    "mithai sweets",
    "bakery cake",
    "cold drink",
    "milkshake",
    "smoothie",
    "energy drink",
    "biscuits",
    "namkeen",
    "chips",
    "popcorn movie",
    "fruit juice",
    "coconut water",

    # ── Groceries ────────────────────────────
    "grocery store",
    "supermarket shopping",
    "vegetables market",
    "fruits purchase",
    "milk eggs bread",
    "bigbasket order",
    "blinkit grocery",
    "zepto delivery",
    "rice wheat flour",
    "cooking oil purchase",
    "dal pulses",
    "sugar salt spices",
    "weekly grocery",
    "household grocery",
    "fresh produce",
    "organic vegetables",
    "dairy products",
    "grocery bill",
    "ration store",
    "monthly grocery",
    "buy bread",
    "buy eggs",
    "buy milk",
    "buy onions",
    "buy tomatoes",
    "buy potatoes",
    "buy rice",
    "buy atta flour",
    "buy oil",
    "butter ghee",
    "curd yogurt",
    "paneer",
    "cheese",
    "buy fruits",
    "apple banana",
    "buy vegetables",
    "spinach methi",
    "buy pulses",
    "buy masala",
    "maggi packet",
    "instant noodles",
    "biscuit packet",
    "snack packet",
    "breakfast cereal",
    "oats",
    "dry fruits",
    "nuts almonds",
    "honey jam",
    "ketchup sauce",
    "cold drink bottle",
    "water bottle",
    "packaged water",
    "soap shampoo",
    "detergent",
    "cleaning supplies",
    "toilet paper",
    "toothpaste",
    "facewash",
    "dunzo grocery",
    "jiomart order",

    # ── Travel ───────────────────────────────
    "uber ride",
    "ola cab",
    "bus ticket",
    "train ticket",
    "flight booking",
    "rapido bike",
    "metro card recharge",
    "auto rickshaw",
    "petrol fuel",
    "toll tax",
    "highway toll",
    "indigo flight",
    "irctc booking",
    "redbus ticket",
    "hotel stay",
    "airbnb booking",
    "taxi airport",
    "parking charges",
    "travel insurance",
    "visa fee",
    "car rental",
    "diesel refill",
    "petrol pump",
    "cab booking",
    "bike fuel",
    "rickshaw ride",
    "share auto",
    "tempo ride",
    "city bus pass",
    "train pass",
    "monthly pass",
    "station parking",
    "highway petrol",
    "road trip fuel",
    "oyo rooms",
    "treebo hotel",
    "zostel hostel",
    "makemytrip booking",
    "goibibo flight",
    "yatra booking",
    "ixigo train",
    "paytm bus",
    "trip expense",
    "tour package",
    "pilgrimage travel",
    "car service oil change",
    "vehicle insurance",
    "fastag recharge",
    "move to pune",
    "move to indore",
    "come from pune",
    "come from indore",
    "coming",
    "going",
    "journey"

    # ── Clothing ─────────────────────────────
    "buy shoes",
    "t shirt purchase",
    "jeans",
    "kurta ethnic wear",
    "saree",
    "formal shirt",
    "dress",
    "jacket winter",
    "sports shoes",
    "sandals footwear",
    "myntra order",
    "ajio clothing",
    "zara clothes",
    "h&m fashion",
    "leggings",
    "underwear socks",
    "school uniform",
    "wedding outfit",
    "sunglasses",
    "belt wallet",
    "handbag purse",
    "blazer suit",
    "salwar kameez",
    "dupatta",
    "lehenga",
    "sherwani",
    "dhoti",
    "pajama nightwear",
    "track pants",
    "gym wear",
    "sports jersey",
    "cap hat",
    "scarf muffler",
    "gloves winter",
    "raincoat umbrella",
    "chappal",
    "kolhapuri sandals",
    "canvas shoes",
    "formal shoes",
    "heels",
    "innerwear",
    "nightsuit",
    "kids clothing",
    "baby clothes",
    "school bag",
    "tie formal",
    "sarojini market",
    "local market clothes",
    "fabric cloth",
    "tailor stitching",

    # ── Tech ─────────────────────────────────
    "monitor purchase",
    "keyboard",
    "laptop",
    "mobile phone",
    "earphones",
    "wireless mouse",
    "usb cable charger",
    "hard drive",
    "pen drive",
    "webcam",
    "printer",
    "router wifi",
    "smartwatch",
    "tablet ipad",
    "graphics card",
    "ram upgrade",
    "power bank",
    "led monitor",
    "gaming controller",
    "mechanical keyboard",
    "laptop bag",
    "phone case cover",
    "new phone",
    "screen protector",
    "bluetooth speaker",
    "airpods",
    "headphones",
    "smart tv",
    "led tv",
    "set top box",
    "cctv camera",
    "electric kettle",
    "trimmer",
    "electric shaver",
    "hair dryer",
    "iron box",
    "extension cord",
    "phone repair",
    "laptop repair",
    "screen replacement",
    "battery replacement",
    "memory card",
    "otg adapter",
    "type c cable",
    "iphone",
    "samsung mobile",
    "oneplus phone",

    # ── Shopping ─────────────────────────────
    "amazon order",
    "flipkart purchase",
    "meesho",
    "online shopping",
    "home decor",
    "furniture purchase",
    "curtains bedsheet",
    "kitchen utensils",
    "stationery office",
    "pen notebook",
    "toy kids",
    "gift item",
    "sports equipment",
    "gym accessories",
    "festive shopping",
    "diwali shopping",
    "book purchase",
    "cosmetics beauty",
    "perfume",
    "watch",
    "jewellery",
    "craft supplies",
    "holi colors",
    "rakhi gift",
    "eid shopping",
    "navratri shopping",
    "ganesh puja items",
    "puja decoration",
    "diyas candles",
    "gift hamper",
    "birthday gift",
    "anniversary gift",
    "flower bouquet",
    "greeting card",
    "return gift",
    "pooja samagri",
    "agarbatti",
    "incense stick",
    "calendar diary",
    "notepad pens",
    "color pencils",
    "art supplies",
    "photo frame",
    "wall clock",
    "dustbin",
    "bucket mug",
    "floor mat",
    "pillow cushion",
    "mirror",
    "storage box",
    "water bottle buy",
    "tiffin box",
    "lunch box",

    # ── Entertainment ─────────────────────────
    "netflix subscription",
    "amazon prime",
    "hotstar subscription",
    "spotify music",
    "youtube premium",
    "movie ticket",
    "pvr cinemas",
    "inox movie",
    "concert ticket",
    "gaming recharge",
    "pubg uc",
    "steam game purchase",
    "ps5 game",
    "amusement park",
    "zoo ticket",
    "museum entry",
    "comedy show",
    "web series binge",
    "apple tv",
    "disney plus",
    "bowling night",
    "escape room",
    "jio cinema",
    "zee5 subscription",
    "sonyliv",
    "mxplayer",
    "ipl match ticket",
    "cricket match",
    "stadium ticket",
    "live show ticket",
    "standup comedy",
    "theatre play",
    "gaming cafe",
    "pool table",
    "snooker parlour",
    "arcade games",
    "board game",
    "cricket bat ball",
    "badminton shuttle",
    "sports club fee",
    "swimming pool ticket",
    "water park entry",
    "theme park",
    "science museum",
    "aquarium ticket",
    "nightclub entry",
    "karaoke bar",
    "disc party night",
    "hookah lounge",
    "wine bar",

    # ── Healthcare ────────────────────────────
    "doctor consultation",
    "doctor fee",
    "doctor visit",
    "hospital bill",
    "hospital charges",
    "medicine pharmacy",
    "health checkup",
    "blood test",
    "dental clinic",
    "dentist fee",
    "eye checkup",
    "physiotherapy",
    "apollo pharmacy",
    "1mg medicine",
    "netmeds order",
    "vaccination",
    "health insurance premium",
    "surgery expense",
    "ambulance",
    "lab report",
    "xray scan",
    "mental health therapy",
    "dietician consultation",
    "vitamins supplements",
    "medical test",
    "clinic visit",
    "nursing home",
    "chemist store",
    "gym membership",
    "yoga class",
    "gym fees",
    "fitness class",
    "zumba class",
    "crossfit",
    "protein powder",
    "whey protein",
    "health supplement",
    "ayurvedic medicine",
    "patanjali medicine",
    "homeopathy",
    "eye glasses",
    "contact lens",
    "first aid kit",
    "thermometer",
    "bp machine",
    "glucometer strips",
    "mri scan",
    "ct scan",
    "ultrasound",
    "ecg test",
    "covid test",
    "dengue test",
    "icu charges",
    "operation expense",
    "fracture plaster",
    "dressing wound",
    "oxygen cylinder",

    # ── Bills ─────────────────────────────────
    "electricity bill",
    "water bill",
    "gas cylinder",
    "broadband internet bill",
    "mobile recharge",
    "dth recharge",
    "dish tv",
    "rent payment",
    "maintenance society",
    "emi loan",
    "credit card bill",
    "insurance premium",
    "property tax",
    "municipality tax",
    "postpaid bill",
    "landline bill",
    "wifi bill",
    "home loan emi",
    "car loan emi",
    "education fee",
    "school fee",
    "tuition fee",
    "gas bill",
    "lpg cylinder",
    "society charges",
    "car insurance",
    "two wheeler insurance",
    "life insurance lic",
    "term insurance",
    "mutual fund sip",
    "jio recharge",
    "airtel recharge",
    "vi recharge",
    "bsnl recharge",
    "tata sky recharge",
    "cable tv bill",
    "coaching fee",
    "college fee",
    "hostel fee",
    "mess fee",
    "library fee",
    "exam fee",
    "personal loan emi",
    "bike loan emi",
    "newspaper bill",
    "milk subscription",
    "maid salary",
    "driver salary",
    "cook salary",
    "security guard salary",
    "fastag toll recharge",
    "ppf contribution",

    # ── Other ─────────────────────────────────
    "atm withdrawal",
    "bank transfer",
    "donation charity",
    "temple offering",
    "newspaper subscription",
    "laundry",
    "dry cleaning",
    "salon haircut",
    "barber shop",
    "spa massage",
    "car wash",
    "repair service",
    "plumber fee",
    "electrician charge",
    "pest control",
    "astrology",
    "legal fee",
    "notary",
    "miscellaneous",
    "cash withdrawal",
    "friend loan",
    "pocket money",
    "mandir donation",
    "gurudwara prasad",
    "charity",
    "pandit fee puja",
    "funeral expense",
    "wedding function",
    "mehendi ceremony",
    "catering wedding",
    "venue booking",
    "decorator",
    "photographer",
    "videographer",
    "party expense",
    "birthday party",
    "baby shower",
    "mundan ceremony",
    "nail salon",
    "threading waxing",
    "facial beauty parlour",
    "mehendi henna",
    "tattoo",
    "passport fee",
    "pan card fee",
    "driving license fee",
    "rto registration",
    "court fee",
    "lawyer consultation",
    "ca accountant fee",
    "photocopy printing",
    "courier parcel",
    "post office",
    "stamp paper",
    "chanda collection",
    "society donation",
    "blood donation camp",
]

labels = [
    *["food"]          * 64,
    *["groceries"]     * 60,
    *["travel"]        * 54,
    *["clothing"]      * 50,
    *["tech"]          * 47,
    *["shopping"]      * 53,
    *["entertainment"] * 50,
    *["healthcare"]    * 57,
    *["bills"]         * 52,
    *["other"]         * 57,
]

assert len(texts) == len(labels), f"Mismatch: {len(texts)} texts vs {len(labels)} labels"

# ─────────────────────────────────────────────
#  PIPELINE
# ─────────────────────────────────────────────
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1, sublinear_tf=True)),
    ("clf",   MultinomialNB(alpha=0.3)),
])

cv_scores = cross_val_score(pipeline, texts, labels, cv=5, scoring="accuracy")
print(f"📊 Cross-val accuracy: {cv_scores.mean():.2%} ± {cv_scores.std():.2%}")

pipeline.fit(texts, labels)
joblib.dump(pipeline, "trained_model.pkl")
print("✅ Model trained and saved → expense_classifier.pkl")

# ─────────────────────────────────────────────
#  SMOKE TESTS
# ─────────────────────────────────────────────
test_cases = [  
    ("buy bread",          "groceries"),
    ("buy eggs",           "groceries"),
    ("buy milk",           "groceries"),
    ("buy onions",         "groceries"),
    ("blinkit order",      "groceries"),
    ("ice cream",          "food"),
    ("kulfi",              "food"),
    ("samosa",             "food"),
    ("biryani",            "food"),
    ("swiggy order",       "food"),
    ("gym membership",     "healthcare"),
    ("gym fees",           "healthcare"),
    ("protein powder",     "healthcare"),
    ("doctor visit",       "healthcare"),
    ("blood test",         "healthcare"),
    ("petrol pump",        "travel"),
    ("ola cab",            "travel"),
    ("irctc booking",      "travel"),
    ("jio recharge",       "bills"),
    ("electricity bill",   "bills"),
    ("lpg cylinder",       "bills"),
    ("diwali shopping",    "shopping"),
    ("amazon order",       "shopping"),
    ("laptop",             "tech"),
    ("samsung mobile",     "tech"),
    ("t shirt purchase",   "clothing"),
    ("kurta ethnic wear",  "clothing"),
    ("movie ticket",       "entertainment"),
    ("netflix subscription","entertainment"),
    ("salon haircut",      "other"),
    ("plumber fee",        "other"),
    ("passport fee",       "other"),
]

print(f"\n🧪 Smoke tests ({len(test_cases)} cases):")
print(f"{'Input':<28} {'Expected':<15} {'Predicted':<15} ✓?")
print("─" * 65)
passed = 0
for text, expected in test_cases:
    predicted = pipeline.predict([text])[0]
    ok = "✅" if predicted == expected else "❌"
    if predicted == expected:
        passed += 1
    print(f"{text:<28} {expected:<15} {predicted:<15} {ok}")

print(f"\n{'🎉' if passed == len(test_cases) else '⚠️ '} {passed}/{len(test_cases)} passed")